name: Flutter Analysis
on:
  push:
    branches:
      - stable
  pull_request:
  workflow_dispatch:

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.0

      - name: install dependencies
        run: flutter pub get

      - name: analyze code
        run: flutter analyze .

      - name: run tests
        run: flutter test