name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: master
          flutter-version: 3.22.0
      - name: Install Package Dependencies
        run: flutter pub get
      - name: Format dart code
        run: dart format .
      - name: Analyze dart code
        run: dart analyze .
      - name: Check publish with dry run
        run: flutter pub publish --dry-run
      - name: Publish package
        run: flutter pub publish -f
